---
homebrew:
  taps:
    - buo/cask-upgrade # useful to upgrade casks
  formula:
    - ansible
    - awscli
    - bash
    - bat
    - black
    - cheat
    - cmake
    - coreutils
    - curl
    - diff-so-fancy
    - direnv
    - eslint
    - eza
    - fd
    - flake8
    - ghq
    - git
    - git-secrets
    - gnu-sed
    - golangci-lint
    - htop
    - hub
    - icdiff
    - isort
    - java
    - jq
    - legit
    - llvm
    - neovim
    - nkf
    - node
    - openssl
    - peco
    - prettier
    - pyenv
    - pyright
    - python
    - rbenv
    - ripgrep
    - ruby
    - ruby-build
    - rust
    - ssh-copy-id
    - terminal-notifier
    - tig
    - tree
    - wget
    - xh
    - zsh
  casks:
    - alfred
    - appcleaner
    - authy
    - dash
    - docker-desktop
    - dropbox
    - evernote
    - google-cloud-sdk
    - google-chrome
    - google-drive
    - google-japanese-ime
    - iterm2
    - maccy
    - omnidisksweeper
    - sequel-ace
    - slack
    - the-unarchiver
    - visual-studio-code
    - vlc
