---
homebrew_packages:
  - ansible
  - autojump
  - bash
  - brew-cask
  - cabal-install
  - coreutils
  - ctags
  - fontconfig
  - freetype
  - gcc
  - gettext
  - ghc
  - git
  - git-flow
  - gnu-sed
  - go
  - httpie
  - hub
  - icdiff
  - llvm
  - nasm
  - nkf
  - node
  - openssl
  - python
  - rbenv
  - readline
  - reattach-to-user-namespace
  - redis
  - rsync
  - ruby
  - ruby-build
  - scala
  - ssh-copy-id
  - terminal-notifier
  - the_silver_searcher
  - tig
  - tmux
  - tree
  - typesafe-activator
  - wget
  - zsh

homebrew_repos:
  - homebrew/dupes
  - caskroom/cask

homebrew_cask_packages:
  - adobe-reader
  - alfred
  - appcleaner
  - disk-inventory-x
  - dropbox
  - evernote
  - google-chrome
  - google-drive
  - google-japanese-ime
  - hex-fiend
  - intellij-idea-ce
  - iterm2
  - java
  - karabiner
  - kobito
  - macdown
  - macvim
  - miro-video-converter
  - sdformatter
  - simple-comic
  - skype
  - slack
  - sublime-text
  - the-unarchiver
  - tunnelblick
  - vagrant
  - virtualbox
  - vlc

